# Form implementation generated from reading ui file 'blinkyWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_blinkyWindow(object):
    def setupUi(self, blinkyWindow):
        blinkyWindow.setObjectName("blinkyWindow")
        blinkyWindow.resize(208, 312)
        self.centralwidget = QtWidgets.QWidget(parent=blinkyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dial = QtWidgets.QDial(parent=self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(0, 30, 191, 141))
        self.dial.setMaximum(100)
        self.dial.setObjectName("dial")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(30, 180, 121, 20))
        self.checkBox.setObjectName("checkBox")
        self.cmbIntervall = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbIntervall.setGeometry(QtCore.QRect(30, 230, 141, 21))
        self.cmbIntervall.setObjectName("cmbIntervall")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 210, 111, 16))
        self.label.setObjectName("label")
        blinkyWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=blinkyWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 208, 26))
        self.menubar.setObjectName("menubar")
        blinkyWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=blinkyWindow)
        self.statusbar.setObjectName("statusbar")
        blinkyWindow.setStatusBar(self.statusbar)

        self.retranslateUi(blinkyWindow)
        QtCore.QMetaObject.connectSlotsByName(blinkyWindow)

    def retranslateUi(self, blinkyWindow):
        _translate = QtCore.QCoreApplication.translate
        blinkyWindow.setWindowTitle(_translate("blinkyWindow", "Qt QTimer example"))
        self.checkBox.setText(_translate("blinkyWindow", "Timer Enabled"))
        self.label.setText(_translate("blinkyWindow", "Timer Intervall [ms]"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    blinkyWindow = QtWidgets.QMainWindow()
    ui = Ui_blinkyWindow()
    ui.setupUi(blinkyWindow)
    blinkyWindow.show()
    sys.exit(app.exec())
