# Form implementation generated from reading ui file 'serialTerminalWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_serialTerminal(object):
    def setupUi(self, serialTerminal):
        serialTerminal.setObjectName("serialTerminal")
        serialTerminal.resize(981, 497)
        self.centralwidget = QtWidgets.QWidget(parent=serialTerminal)
        self.centralwidget.setObjectName("centralwidget")
        self.txtRecieved = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.txtRecieved.setEnabled(False)
        self.txtRecieved.setGeometry(QtCore.QRect(10, 90, 961, 351))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.txtRecieved.setFont(font)
        self.txtRecieved.setObjectName("txtRecieved")
        self.txtToSend = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txtToSend.setGeometry(QtCore.QRect(10, 50, 871, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.txtToSend.setFont(font)
        self.txtToSend.setObjectName("txtToSend")
        self.btnSend = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSend.setGeometry(QtCore.QRect(880, 50, 81, 41))
        self.btnSend.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("send.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnSend.setIcon(icon)
        self.btnSend.setIconSize(QtCore.QSize(32, 32))
        self.btnSend.setObjectName("btnSend")
        self.cmbSerialPorts = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbSerialPorts.setGeometry(QtCore.QRect(840, 0, 121, 41))
        self.cmbSerialPorts.setCurrentText("")
        self.cmbSerialPorts.setObjectName("cmbSerialPorts")
        self.labSerialPortStatusDisconnected = QtWidgets.QLabel(parent=self.centralwidget)
        self.labSerialPortStatusDisconnected.setGeometry(QtCore.QRect(798, 4, 32, 32))
        self.labSerialPortStatusDisconnected.setText("")
        self.labSerialPortStatusDisconnected.setPixmap(QtGui.QPixmap("power_off.svg"))
        self.labSerialPortStatusDisconnected.setScaledContents(True)
        self.labSerialPortStatusDisconnected.setObjectName("labSerialPortStatusDisconnected")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 87 14pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.labSerialPortStatusConected = QtWidgets.QLabel(parent=self.centralwidget)
        self.labSerialPortStatusConected.setGeometry(QtCore.QRect(798, 4, 32, 32))
        self.labSerialPortStatusConected.setText("")
        self.labSerialPortStatusConected.setPixmap(QtGui.QPixmap("electrical_services.svg"))
        self.labSerialPortStatusConected.setScaledContents(True)
        self.labSerialPortStatusConected.setObjectName("labSerialPortStatusConected")
        self.cmbSerialCommands = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbSerialCommands.setGeometry(QtCore.QRect(170, 0, 311, 41))
        self.cmbSerialCommands.setObjectName("cmbSerialCommands")
        serialTerminal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=serialTerminal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 26))
        self.menubar.setObjectName("menubar")
        serialTerminal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=serialTerminal)
        self.statusbar.setObjectName("statusbar")
        serialTerminal.setStatusBar(self.statusbar)

        self.retranslateUi(serialTerminal)
        QtCore.QMetaObject.connectSlotsByName(serialTerminal)

    def retranslateUi(self, serialTerminal):
        _translate = QtCore.QCoreApplication.translate
        serialTerminal.setWindowTitle(_translate("serialTerminal", "Serial Terminal "))
        self.txtRecieved.setPlainText(_translate("serialTerminal", "Text recieved from Microcontroller"))
        self.txtToSend.setPlaceholderText(_translate("serialTerminal", "Text to send to Microcontroller"))
        self.label_2.setText(_translate("serialTerminal", "Serial Terminal "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    serialTerminal = QtWidgets.QMainWindow()
    ui = Ui_serialTerminal()
    ui.setupUi(serialTerminal)
    serialTerminal.show()
    sys.exit(app.exec())
