# Form implementation generated from reading ui file 'loginDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(631, 469)
        LoginDialog.setStyleSheet("background-color: #FFFFFF;\n"
"")
        LoginDialog.setModal(True)
        self.label = QtWidgets.QLabel(parent=LoginDialog)
        self.label.setGeometry(QtCore.QRect(340, 30, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=LoginDialog)
        self.label_2.setGeometry(QtCore.QRect(360, 130, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=LoginDialog)
        self.label_3.setGeometry(QtCore.QRect(360, 221, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=LoginDialog)
        self.lineEditEmail.setGeometry(QtCore.QRect(370, 153, 250, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditEmail.setFont(font)
        self.lineEditEmail.setStyleSheet("padding: 1px;\n"
"border-style: solid;\n"
"border: 2px solid gray;\n"
"border-radius: 8px;\n"
"padding-left: 40px;")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=LoginDialog)
        self.lineEditPassword.setGeometry(QtCore.QRect(370, 243, 250, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditPassword.setFont(font)
        self.lineEditPassword.setStyleSheet("lineedit-password-character: 9679;\n"
"lineedit-password-mask-delay: 1000; \n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 2px solid gray;\n"
"border-radius: 8px;\n"
"padding-left: 40px;\n"
"\n"
"")
        self.lineEditPassword.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhNoAutoUppercase|QtCore.Qt.InputMethodHint.ImhNoPredictiveText|QtCore.Qt.InputMethodHint.ImhSensitiveData)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.label_4 = QtWidgets.QLabel(parent=LoginDialog)
        self.label_4.setGeometry(QtCore.QRect(380, 163, 31, 20))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Images/mail.svg"))
        self.label_4.setObjectName("label_4")
        self.labelVisibility = QtWidgets.QLabel(parent=LoginDialog)
        self.labelVisibility.setGeometry(QtCore.QRect(372, 245, 31, 37))
        self.labelVisibility.setStyleSheet("QLabel {\n"
"      border-radius: 6px;\n"
"  }\n"
"\n"
"QLabel:hover {\n"
"                background-color:#E0E0E0;\n"
"            }\n"
"QLabel:pressed {\n"
"                background-color:#C0C0C0;\n"
"            }\n"
"")
        self.labelVisibility.setText("")
        self.labelVisibility.setPixmap(QtGui.QPixmap("Images/visibility.svg"))
        self.labelVisibility.setObjectName("labelVisibility")
        self.pushButton = QtWidgets.QPushButton(parent=LoginDialog)
        self.pushButton.setGeometry(QtCore.QRect(370, 370, 250, 51))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"              border: 1px  #FF7A7A;\n"
"             border-radius: 20px;\n"
"             background-color: #FF7A7A;\n"
"            }            \n"
"QPushButton:hover {\n"
"                background-color:#F07070;;\n"
"            }\n"
"\n"
"QPushButton:pressed  {\n"
"                background-color:#C07070;;\n"
"            }\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(parent=LoginDialog)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 381, 301))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Images/login.svg"))
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=LoginDialog)
        self.label_6.setGeometry(QtCore.QRect(0, 240, 631, 232))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Images/login_bottom.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_6.raise_()
        self.label_5.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEditEmail.raise_()
        self.lineEditPassword.raise_()
        self.label_4.raise_()
        self.labelVisibility.raise_()
        self.pushButton.raise_()

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Dialog"))
        self.label.setText(_translate("LoginDialog", "Login"))
        self.label_2.setText(_translate("LoginDialog", "Email"))
        self.label_3.setText(_translate("LoginDialog", "Password"))
        self.lineEditEmail.setText(_translate("LoginDialog", "rul@usn.no"))
        self.lineEditPassword.setText(_translate("LoginDialog", "Rune"))
        self.pushButton.setText(_translate("LoginDialog", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginDialog = QtWidgets.QDialog()
    ui = Ui_LoginDialog()
    ui.setupUi(LoginDialog)
    LoginDialog.show()
    sys.exit(app.exec())
