# Form implementation generated from reading ui file 'serialPlotterWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_serialPlotter(object):
    def setupUi(self, serialPlotter):
        serialPlotter.setObjectName("serialPlotter")
        serialPlotter.resize(981, 497)
        self.centralwidget = QtWidgets.QWidget(parent=serialPlotter)
        self.centralwidget.setObjectName("centralwidget")
        self.cmbSerialPorts = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbSerialPorts.setGeometry(QtCore.QRect(840, 0, 121, 41))
        self.cmbSerialPorts.setCurrentText("")
        self.cmbSerialPorts.setObjectName("cmbSerialPorts")
        self.labSerialPortStatusDisconnected = QtWidgets.QLabel(parent=self.centralwidget)
        self.labSerialPortStatusDisconnected.setGeometry(QtCore.QRect(798, 4, 32, 32))
        self.labSerialPortStatusDisconnected.setText("")
        self.labSerialPortStatusDisconnected.setPixmap(QtGui.QPixmap("power_off.svg"))
        self.labSerialPortStatusDisconnected.setScaledContents(True)
        self.labSerialPortStatusDisconnected.setObjectName("labSerialPortStatusDisconnected")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 87 14pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.labSerialPortStatusConected = QtWidgets.QLabel(parent=self.centralwidget)
        self.labSerialPortStatusConected.setGeometry(QtCore.QRect(798, 4, 32, 32))
        self.labSerialPortStatusConected.setText("")
        self.labSerialPortStatusConected.setPixmap(QtGui.QPixmap("electrical_services.svg"))
        self.labSerialPortStatusConected.setScaledContents(True)
        self.labSerialPortStatusConected.setObjectName("labSerialPortStatusConected")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 100, 621, 251))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setObjectName("label")
        serialPlotter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=serialPlotter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 26))
        self.menubar.setObjectName("menubar")
        serialPlotter.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=serialPlotter)
        self.statusbar.setObjectName("statusbar")
        serialPlotter.setStatusBar(self.statusbar)

        self.retranslateUi(serialPlotter)
        QtCore.QMetaObject.connectSlotsByName(serialPlotter)

    def retranslateUi(self, serialPlotter):
        _translate = QtCore.QCoreApplication.translate
        serialPlotter.setWindowTitle(_translate("serialPlotter", "Serial Plotter "))
        self.label_2.setText(_translate("serialPlotter", "Serial Plotter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    serialPlotter = QtWidgets.QMainWindow()
    ui = Ui_serialPlotter()
    ui.setupUi(serialPlotter)
    serialPlotter.show()
    sys.exit(app.exec())
